/**
 * BrandDemo — sample reel showing every brand component for one channel theme.
 *
 * Renders ~78 seconds @ 24fps showing CharacterCard, TypewriterText, AssetFrame
 * (3 variants), CTABanner (1 preset), AnimatedMap (4 variants), Timeline
 * (4 variants). Used for component validation before locking the brand library.
 *
 * Theme is loaded from a per-channel JSON file generated by the Python
 * brand_assets/tokens/playbook_to_tokens.py bridge.
 */
import { AbsoluteFill, Series, staticFile, OffthreadVideo } from "remotion";
import {
  CharacterCard,
  TypewriterText,
  CTABanner,
  AssetFrame,
  AnimatedMap,
  Timeline,
  BrandTheme,
  resolveTheme,
} from "./components";
import huxleyTheme from "./components/brand/themes/grandpa_huxley.json";
import mmTheme from "./components/brand/themes/midnight_magnates.json";

export interface BrandDemoProps {
  channel: "grandpa_huxley" | "midnight_magnates";
}

const THEMES: Record<BrandDemoProps["channel"], Partial<BrandTheme>> = {
  grandpa_huxley: huxleyTheme as Partial<BrandTheme>,
  midnight_magnates: mmTheme as Partial<BrandTheme>,
};

const FPS = 24;
const sec = (s: number) => Math.round(s * FPS);

export const BrandDemo: React.FC<BrandDemoProps> = ({ channel }) => {
  const theme = resolveTheme(THEMES[channel]);
  const isMM = channel === "midnight_magnates";

  // Channel-specific demo content
  const figure1 = isMM
    ? {
        name: "Mayer Amschel Rothschild",
        role: "Founder of the Rothschild banking dynasty",
        dates: "1744 – 1812",
        stats: ["Frankfurt → London → Paris → Vienna → Naples", "Five sons, five capitals"] as [string, string],
      }
    : {
        name: "Marcus Aurelius",
        role: "Stoic philosopher and Roman emperor",
        dates: "121 – 180 AD",
        stats: ["Last of the Five Good Emperors", "Author of Meditations"] as [string, string],
      };

  const figure2 = isMM
    ? {
        name: "The Medici Bank",
        role: "Most influential financial institution of 15th c. Europe",
        dates: "1397 – 1494",
        stats: ["Florence headquarters, 11 branches", "Funded the Renaissance"] as [string, string],
      }
    : {
        name: "Lao Tzu",
        role: "Founding figure of Taoist philosophy",
        dates: "c. 6th c. BC",
        stats: ["Author of the Tao Te Ching", "Keeper of the imperial archives"] as [string, string],
      };

  const channelTitle = isMM ? "MIDNIGHT MAGNATES" : "GRANDPA HUXLEY";
  const channelSubtitle = isMM
    ? "Hidden history of power, wealth, and human nature"
    : "Wisdom for sleep — philosophy, history, and the quiet hours";

  const photo1 = isMM ? staticFile("brand_demo/mm/vault.jpg") : staticFile("brand_demo/huxley/candle.jpg");
  const photo2 = isMM ? staticFile("brand_demo/mm/chess.jpg") : staticFile("brand_demo/huxley/book.jpg");
  const clip = isMM ? staticFile("brand_demo/mm/skyline.mp4") : staticFile("brand_demo/huxley/fireplace.mp4");

  // Map config — channel-specific story
  const routeMap = isMM
    ? {
        variant: "world_route" as const,
        origin: { x: 488, y: 122, label: "Frankfurt" },
        destination: { x: 460, y: 130, label: "London" },
        waypoints: [
          { x: 478, y: 132, label: "Paris" },
          { x: 525, y: 130, label: "Vienna" },
          { x: 540, y: 175, label: "Naples" },
        ],
        highlightContinents: [2],
      }
    : {
        variant: "world_route" as const,
        origin: { x: 595, y: 150, label: "Constantinople" },
        destination: { x: 510, y: 130, label: "Rome" },
        waypoints: [{ x: 555, y: 145, label: "Athens" }],
        highlightContinents: [2, 3],
      };

  const zoomMap = isMM
    ? { variant: "region_zoom" as const, target: { x: 480, y: 132, label: "London" }, endZoom: 4, highlightContinents: [2] }
    : { variant: "region_zoom" as const, target: { x: 525, y: 130, label: "Athens" }, endZoom: 4, highlightContinents: [2] };

  const pinMap = isMM
    ? {
        variant: "pin_drop" as const,
        pins: [
          { x: 490, y: 122, label: "Frankfurt" },
          { x: 455, y: 130, label: "London" },
          { x: 478, y: 130, label: "Paris" },
          { x: 525, y: 130, label: "Vienna" },
          { x: 540, y: 175, label: "Naples" },
        ],
      }
    : {
        variant: "pin_drop" as const,
        pins: [
          { x: 510, y: 130, label: "Rome" },
          { x: 525, y: 130, label: "Athens" },
          { x: 595, y: 150, label: "Antioch" },
          { x: 540, y: 175, label: "Alexandria" },
        ],
      };

  const empireMap = isMM
    ? {
        variant: "empire_extent" as const,
        // British East India Co. trading reach (illustrative polygon over Asia/Africa/Europe)
        territoryPath:
          "M 480,110 L 560,110 L 660,150 L 800,180 L 820,250 L 770,280 L 670,260 L 560,220 L 500,180 Z",
        direction: "rise" as const,
      }
    : {
        variant: "empire_extent" as const,
        // Roman Empire approximate extent
        territoryPath:
          "M 460,115 L 580,115 L 615,160 L 590,195 L 530,205 L 490,195 L 470,165 Z",
        direction: "rise" as const,
      };

  // Timeline content
  const horizontalEvents = isMM
    ? [
        { year: "1744", label: "Mayer born", type: "birth" as const },
        { year: "1764", label: "Banking start", type: "milestone" as const },
        { year: "1798", label: "London branch", type: "rise" as const },
        { year: "1815", label: "Waterloo bond coup", type: "milestone" as const },
        { year: "1850", label: "Network at peak", type: "milestone" as const },
      ]
    : [
        { year: "470 BC", label: "Socrates born", type: "birth" as const },
        { year: "399 BC", label: "Trial and death", type: "death" as const },
        { year: "387 BC", label: "Plato founds the Academy", type: "milestone" as const },
        { year: "335 BC", label: "Aristotle's Lyceum", type: "milestone" as const },
        { year: "301 BC", label: "Zeno founds Stoicism", type: "rise" as const },
      ];

  const verticalEvents = isMM
    ? [
        { year: "Chapter 1", label: "Frankfurt's Hidden Trade", description: "How a single Jewish quarter became Europe's information capital." },
        { year: "Chapter 2", label: "Five Sons, Five Capitals", description: "The deliberate scattering that built the network." },
        { year: "Chapter 3", label: "Waterloo and the Bond Market", description: "The information advantage that became legend." },
        { year: "Chapter 4", label: "What the Network Outlasted", description: "Empires fell. The system did not." },
      ]
    : [
        { year: "Chapter 1", label: "The Marketplace at Athens", description: "Where philosophy was an argument, not a textbook." },
        { year: "Chapter 2", label: "The Hemlock and the Cup", description: "What Socrates chose, and why." },
        { year: "Chapter 3", label: "The Stoic Inheritance", description: "How a slave's lecture notes outlasted the empire." },
        { year: "Chapter 4", label: "What Endures", description: "The quiet thread from Athens to your reading chair." },
      ];

  const dynastyLifelines = isMM
    ? [
        {
          name: "Mayer Amschel",
          startYear: "1744",
          endYear: "1812",
          events: [
            { year: "1764", label: "Banking start" },
            { year: "1798", label: "Sons dispatched" },
          ],
        },
        {
          name: "Nathan (London)",
          startYear: "1777",
          endYear: "1836",
          events: [
            { year: "1798", label: "Arrives London" },
            { year: "1815", label: "Waterloo coup" },
          ],
        },
        {
          name: "James (Paris)",
          startYear: "1792",
          endYear: "1868",
          events: [
            { year: "1812", label: "Paris branch" },
            { year: "1842", label: "Rail empire" },
          ],
        },
      ]
    : [
        {
          name: "Socrates",
          startYear: "470 BC",
          endYear: "399 BC",
          events: [{ year: "440 BC", label: "Teaching" }, { year: "399 BC", label: "Trial" }],
        },
        {
          name: "Plato",
          startYear: "428 BC",
          endYear: "348 BC",
          events: [{ year: "387 BC", label: "Academy" }, { year: "360 BC", label: "Republic" }],
        },
        {
          name: "Aristotle",
          startYear: "384 BC",
          endYear: "322 BC",
          events: [{ year: "367 BC", label: "Joins Academy" }, { year: "335 BC", label: "Lyceum" }],
        },
      ];

  const branching = isMM
    ? {
        branchPoint: { year: "1815", label: "News from Waterloo" },
        branches: [
          { label: "Sell publicly", outcome: "Crowd panics, prices crash, Rothschilds buy at the bottom.", taken: true },
          { label: "Buy openly", outcome: "Network exposed, advantage burnt — would have lost the long game.", taken: false },
        ],
      }
    : {
        branchPoint: { year: "399 BC", label: "Athens offers exile" },
        branches: [
          { label: "Drink the hemlock", outcome: "Becomes a philosopher's death — the Apology echoes for 2400 years.", taken: true },
          { label: "Accept exile", outcome: "Lives. Teaches. But the moral force is gone, and history forgets.", taken: false },
        ],
      };

  return (
    <AbsoluteFill style={{ background: theme.bg }}>
      <Series>
        {/* 0:00–0:05 — Title intro */}
        <Series.Sequence durationInFrames={sec(5)}>
          <TypewriterText
            text={`${channelTitle}\nbrand component showcase`}
            charsPerSecond={14}
            fontSize={64}
            theme={theme}
            durationFrames={sec(5)}
          />
        </Series.Sequence>

        {/* 0:05–0:11 — CharacterCard top-right */}
        <Series.Sequence durationInFrames={sec(6)}>
          <AbsoluteFill style={{ background: theme.bg }}>
            <div
              style={{
                position: "absolute",
                top: 80,
                left: 80,
                fontFamily: theme.fontHeading,
                color: theme.muted,
                fontSize: 22,
                letterSpacing: "0.08em",
              }}
            >
              CharacterCard · sceneIndex=0 (top-right)
            </div>
            <CharacterCard {...figure1} sceneIndex={0} durationFrames={sec(6)} theme={theme} />
          </AbsoluteFill>
        </Series.Sequence>

        {/* 0:11–0:17 — CharacterCard top-left (alternating) */}
        <Series.Sequence durationInFrames={sec(6)}>
          <AbsoluteFill style={{ background: theme.bg }}>
            <div
              style={{
                position: "absolute",
                top: 80,
                right: 80,
                fontFamily: theme.fontHeading,
                color: theme.muted,
                fontSize: 22,
                letterSpacing: "0.08em",
                textAlign: "right",
              }}
            >
              CharacterCard · sceneIndex=1 (top-left)
            </div>
            <CharacterCard {...figure2} sceneIndex={1} durationFrames={sec(6)} theme={theme} />
          </AbsoluteFill>
        </Series.Sequence>

        {/* 0:17–0:22 — AssetFrame parchment with photo */}
        <Series.Sequence durationInFrames={sec(5)}>
          <AssetFrame
            variant="parchment"
            src={photo1}
            captionText={isMM ? "The vault as power's quiet symbol" : "A single candle, a quiet hour"}
            theme={theme}
            durationFrames={sec(5)}
          />
        </Series.Sequence>

        {/* 0:22–0:27 — AssetFrame boardroom with photo */}
        <Series.Sequence durationInFrames={sec(5)}>
          <AssetFrame
            variant="boardroom"
            src={photo2}
            captionText={isMM ? "Strategy, played slow" : "What a single book can hold"}
            theme={theme}
            durationFrames={sec(5)}
          />
        </Series.Sequence>

        {/* 0:27–0:33 — AssetFrame document with stamp (MM) or polaroid (Huxley) */}
        <Series.Sequence durationInFrames={sec(6)}>
          {isMM ? (
            <AssetFrame
              variant="document"
              src={photo1}
              stamp="CLASSIFIED"
              captionText="The kind of paper most never see"
              theme={theme}
              durationFrames={sec(6)}
            />
          ) : (
            <AssetFrame
              variant="polaroid"
              src={photo2}
              captionText="A keepsake, a quiet remembrance"
              theme={theme}
              durationFrames={sec(6)}
            />
          )}
        </Series.Sequence>

        {/* 0:33–0:39 — AssetFrame filmstrip wrapping a stock video */}
        <Series.Sequence durationInFrames={sec(6)}>
          <AssetFrame variant="filmstrip" theme={theme} durationFrames={sec(6)}>
            <OffthreadVideo
              src={clip}
              style={{ width: "100%", height: "100%", objectFit: "cover" }}
            />
          </AssetFrame>
        </Series.Sequence>

        {/* 0:39–0:46 — AnimatedMap world_route */}
        <Series.Sequence durationInFrames={sec(7)}>
          <AnimatedMap
            config={routeMap}
            title="WORLD ROUTE"
            theme={theme}
            durationFrames={sec(7)}
          />
        </Series.Sequence>

        {/* 0:46–0:52 — AnimatedMap region_zoom */}
        <Series.Sequence durationInFrames={sec(6)}>
          <AnimatedMap
            config={zoomMap}
            title="REGION ZOOM"
            theme={theme}
            durationFrames={sec(6)}
          />
        </Series.Sequence>

        {/* 0:52–0:59 — AnimatedMap pin_drop */}
        <Series.Sequence durationInFrames={sec(7)}>
          <AnimatedMap
            config={pinMap}
            title="PIN DROP"
            theme={theme}
            durationFrames={sec(7)}
          />
        </Series.Sequence>

        {/* 0:59–1:05 — AnimatedMap empire_extent */}
        <Series.Sequence durationInFrames={sec(6)}>
          <AnimatedMap
            config={empireMap}
            title="EMPIRE EXTENT"
            theme={theme}
            durationFrames={sec(6)}
          />
        </Series.Sequence>

        {/* 1:05–1:11 — Timeline horizontal */}
        <Series.Sequence durationInFrames={sec(6)}>
          <Timeline
            variant="horizontal"
            events={horizontalEvents}
            title="TIMELINE · HORIZONTAL"
            theme={theme}
            durationFrames={sec(6)}
          />
        </Series.Sequence>

        {/* 1:11–1:18 — Timeline vertical_chapter */}
        <Series.Sequence durationInFrames={sec(7)}>
          <Timeline
            variant="vertical_chapter"
            events={verticalEvents}
            title="TIMELINE · VERTICAL CHAPTER"
            theme={theme}
            durationFrames={sec(7)}
          />
        </Series.Sequence>

        {/* 1:18–1:25 — Timeline dynasty */}
        <Series.Sequence durationInFrames={sec(7)}>
          <Timeline
            variant="dynasty"
            lifelines={dynastyLifelines}
            title="TIMELINE · DYNASTY"
            theme={theme}
            durationFrames={sec(7)}
          />
        </Series.Sequence>

        {/* 1:25–1:32 — Timeline branching */}
        <Series.Sequence durationInFrames={sec(7)}>
          <Timeline
            variant="branching"
            branchPoint={branching.branchPoint}
            branches={branching.branches}
            title="TIMELINE · BRANCHING"
            theme={theme}
            durationFrames={sec(7)}
          />
        </Series.Sequence>

        {/* 1:32–1:38 — CTABanner */}
        <Series.Sequence durationInFrames={sec(6)}>
          <AbsoluteFill style={{ background: theme.bg }}>
            <div
              style={{
                position: "absolute",
                top: "40%",
                left: "50%",
                transform: "translate(-50%, -50%)",
                fontFamily: theme.fontHeading,
                fontSize: 36,
                color: theme.text,
                textAlign: "center",
                maxWidth: "70%",
                lineHeight: 1.3,
              }}
            >
              {channelSubtitle}
            </div>
            <CTABanner
              preset={isMM ? "spotify_follow" : "youtube_subscribe"}
              holdSeconds={4}
              theme={theme}
              durationFrames={sec(6)}
            />
          </AbsoluteFill>
        </Series.Sequence>
      </Series>
    </AbsoluteFill>
  );
};

export const BRAND_DEMO_DURATION_FRAMES = sec(98); // 0:05+0:06+0:06+0:05+0:05+0:06+0:06+0:07+0:06+0:07+0:06+0:06+0:07+0:07+0:07+0:06 = 98s
